// Generated from: features\Program.feature
import { test } from "../../Fixtures/fixtures.js";

test.describe('Program page validation', () => {

  test.beforeEach('Background', async ({ Given, classpagefixture, When }) => {
    await Given('Admin logs in to LMS application and lands on home page', null, { classpagefixture }); 
    await When('Admin clicks the "Program" Navigation bar in the Header', null, { classpagefixture }); 
  });
  
  test('Verify delete feature', async ({ When, programpagefixture, Then }) => { 
    await When('Admin clicks on delete button for a program', null, { programpagefixture }); 
    await Then('Admin will get confirm deletion popup', null, { programpagefixture }); 
  });

  test.skip('Verify Admin is able to click \'Yes\'', { tag: ['@skip'] }, async ({ Given, When, Then }) => { 
    await Given('Admin is on Confirm deletion form'); 
    await When('Admin clicks on yesbutton"Yes" button'); 
    await Then('Admin can see \'SuccessfulProgram Deleted\' message'); 
  });

  test.skip('Verify Admin is able to delete program', { tag: ['@skip'] }, async ({ When, Then }) => { 
    await When('Admin Searches for "Deleted Program name"'); 
    await Then('There should seee zero results.'); 
  });

  test('Verify Admin is able to click \'No\'', async ({ Given, programpagefixture, When, Then }) => { 
    await Given('Admin is on Program Confirm Deletion Page after selecting a program to delete', null, { programpagefixture }); 
    await When('Admin clicks on nobutton"No" button', null, { programpagefixture }); 
    await Then('Admin can see Confirmation form disappears', null, { programpagefixture }); 
  });

  test('Verify Admin is able to close the window with "X"', async ({ Given, programpagefixture, When, Then }) => { 
    await Given('Admin is on Program Confirm Deletion Page after selecting a program to delete', null, { programpagefixture }); 
    await When('Admin Click on "X" button', null, { programpagefixture }); 
    await Then('Admin can see Confirm Deletion form disappear', null, { programpagefixture }); 
  });

  test('Verify Admin is able to select multiple programs', async ({ When, programpagefixture, Then }) => { 
    await When('Admin selects more than one program by clicking on the checkbox', null, { programpagefixture }); 
    await Then('Programs get selected', null, { programpagefixture }); 
  });

  test('Verify Admin is able to delete Multiple programs', async ({ When, programpagefixture, Then }) => { 
    await When('Admin clicks on the delete button on the left top of the program page', null, { programpagefixture }); 
    await Then('Admin lands on Confirmation form', null, { programpagefixture }); 
  });

  test.skip('Verify Admin is able to click \'Yes\' - Delete multiple programes', { tag: ['@skip'] }, async ({ Given, When, Then }) => { 
    await Given('Admin is on Confirm deletion form'); 
    await When('Admin clicks on yesbutton"Yes" button'); 
    await Then('Admin can see \'SuccessfulProgram Deleted\' message'); 
  });

  test.skip('Verify Admin is able to deleted program', { tag: ['@skip'] }, async ({ When, Then }) => { 
    await When('Admin Searches for Deleted Program names'); 
    await Then('There should be zero results'); 
  });

  test('Verify Admin is able to click \'No\'-multiple programes are deleted', async ({ Given, programpagefixture, When, Then }) => { 
    await Given('Admin is on Confirm deletion form-multiple programes selected to delete', null, { programpagefixture }); 
    await When('Admin clicks on nobutton"No" button-multiple programes selected to delete', null, { programpagefixture }); 
    await Then('Admin can see Programs are still selected and not deleted', null, { programpagefixture }); 
  });

  test('Verify Admin is able to search results found for program name', async ({ When, programpagefixture, page, Then }) => { 
    await When('Admin enter the program to search By program name', null, { programpagefixture, page }); 
    await Then('Admin should able to see Program name, description, and status for searched program name', null, { page }); 
  });

  test('Verify Admin is able to search results found for program description', async ({ When, programpagefixture, page, Then }) => { 
    await When('Admin enter the program to search By program description', null, { programpagefixture, page }); 
    await Then('Admin should able to see Program name, description, and status for searched program description', null, { page }); 
  });

  test('Verify Admin is able to search results not found', async ({ When, programpagefixture, page, Then }) => { 
    await When('Admin enter the program to search By program name that does not exist', null, { programpagefixture, page }); 
    await Then('There should be zero results - Search bar', null, { page }); 
  });

  test('Verify Admin is able to search with partial program name', async ({ When, programpagefixture, page, Then }) => { 
    await When('Admin enter the program to search By partial name of program', null, { programpagefixture, page }); 
    await Then('Admin should able to see Program name, description, and status for searched program name - for partial name search', null, { page }); 
  });

  test.describe('Verify sorting of "<column Name>" in Ascending order', () => {

    test('Verify sorting of "Program Name" in Ascending order', async ({ When, commonpagefixture, Then }) => { 
      await When('Admin clicks on Arrow next to "Program Name" to sort in Ascending order', null, { commonpagefixture }); 
      await Then('Admin See the "Program Name" is sorted in Ascending order', null, { commonpagefixture }); 
    });

    test('Verify sorting of "Program Description" in Ascending order', async ({ When, commonpagefixture, Then }) => { 
      await When('Admin clicks on Arrow next to "Program Description" to sort in Ascending order', null, { commonpagefixture }); 
      await Then('Admin See the "Program Description" is sorted in Ascending order', null, { commonpagefixture }); 
    });

    test('Verify sorting of "Program Status" in Ascending order', async ({ When, commonpagefixture, Then }) => { 
      await When('Admin clicks on Arrow next to "Program Status" to sort in Ascending order', null, { commonpagefixture }); 
      await Then('Admin See the "Program Status" is sorted in Ascending order', null, { commonpagefixture }); 
    });

  });

  test.describe('Verify sorting of "<column Name>" in Descending order', () => {

    test('Verify sorting of "Program Name" in Descending order', async ({ When, commonpagefixture, Then }) => { 
      await When('Admin clicks on Arrow next to "Program Name" to sort in Descending order', null, { commonpagefixture }); 
      await Then('Admin See the "Program Name" is sorted in Descending order', null, { commonpagefixture }); 
    });

    test('Verify sorting of "Program Description" in Descending order', async ({ When, commonpagefixture, Then }) => { 
      await When('Admin clicks on Arrow next to "Program Description" to sort in Descending order', null, { commonpagefixture }); 
      await Then('Admin See the "Program Description" is sorted in Descending order', null, { commonpagefixture }); 
    });

    test('Verify sorting of "Program Status" in Descending order', async ({ When, commonpagefixture, Then }) => { 
      await When('Admin clicks on Arrow next to "Program Status" to sort in Descending order', null, { commonpagefixture }); 
      await Then('Admin See the "Program Status" is sorted in Descending order', null, { commonpagefixture }); 
    });

  });

  test('Verify Admin is able to click \'Next page\' link', async ({ When, commonpagefixture, Then }) => { 
    await When('Admin clicks "Next page" link on the "Program" table', null, { commonpagefixture }); 
    await Then('Admin should see the next page record on the table  with Pagination has previous active link enabled', null, { commonpagefixture }); 
  });

  test('Verify Admin is able to click \'Last page\' link', async ({ When, commonpagefixture, Then }) => { 
    await When('Admin clicks "Last page" link on the "Program" table', null, { commonpagefixture }); 
    await Then('Admin should see the last page record on the table with Next page link and last page links are disabled', null, { commonpagefixture }); 
  });

  test('Verify Admin is able to click \'Previous page\' link', async ({ Given, commonpagefixture, When, Then }) => { 
    await Given('Admin is on last page of "Program" module table', null, { commonpagefixture }); 
    await When('Admin clicks "Previous page" link on the "Program" table', null, { commonpagefixture }); 
    await Then('Admin should see the previous page record on the table with pagination has next page and last page link enabled', null, { commonpagefixture }); 
  });

  test('Verify Admin is able to click First page link', async ({ Given, commonpagefixture, When, Then }) => { 
    await Given('Admin is on last page of "Program" module table', null, { commonpagefixture }); 
    await When('Admin clicks "First page" link on the "Program" table', null, { commonpagefixture }); 
    await Then('Admin should see the very first page record on the table with Previous page link and first page links are disabled', null, { commonpagefixture }); 
  });

  test('Validating the program manage page', async ({ Then, classpagefixture }) => { 
    await Then('Admin should land on the " Manage Program" page', null, { classpagefixture }); 
  });

  test('Verify Logout displayed in menu bar', async ({ Then, programpagefixture }) => { 
    await Then('Admin should see "Logout" in menu bar', null, { programpagefixture }); 
  });

});

// == technical section ==

test.afterEach('AfterEach Hooks', ({ $afterEach }) => {});

test.use({
  $test: ({}, use) => use(test),
  $uri: ({}, use) => use('features\\Program.feature'),
  $bddFileData: ({}, use) => use(bddFileData),
  $afterEachFixtures: ({ page }, use) => use({ page }),
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":11,"pickleLine":9,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"When Admin clicks on delete button for a program","stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"Then Admin will get confirm deletion popup","stepMatchArguments":[]}]},
  {"pwTestLine":16,"pickleLine":14,"skipped":true,"tags":["@skip"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true},{"pwStepLine":17,"gherkinStepLine":15,"keywordType":"Context","textWithKeyword":"Given Admin is on Confirm deletion form"},{"pwStepLine":18,"gherkinStepLine":16,"keywordType":"Action","textWithKeyword":"When Admin clicks on yesbutton\"Yes\" button"},{"pwStepLine":19,"gherkinStepLine":17,"keywordType":"Outcome","textWithKeyword":"Then Admin can see 'SuccessfulProgram Deleted' message"}]},
  {"pwTestLine":22,"pickleLine":19,"skipped":true,"tags":["@skip"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true},{"pwStepLine":23,"gherkinStepLine":21,"keywordType":"Action","textWithKeyword":"When Admin Searches for \"Deleted Program name\""},{"pwStepLine":24,"gherkinStepLine":22,"keywordType":"Outcome","textWithKeyword":"Then There should seee zero results."}]},
  {"pwTestLine":27,"pickleLine":24,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":25,"keywordType":"Context","textWithKeyword":"Given Admin is on Program Confirm Deletion Page after selecting a program to delete","stepMatchArguments":[]},{"pwStepLine":29,"gherkinStepLine":26,"keywordType":"Action","textWithKeyword":"When Admin clicks on nobutton\"No\" button","stepMatchArguments":[{"group":{"start":24,"value":"\"No\"","children":[{"start":25,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":27,"keywordType":"Outcome","textWithKeyword":"Then Admin can see Confirmation form disappears","stepMatchArguments":[]}]},
  {"pwTestLine":33,"pickleLine":29,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":34,"gherkinStepLine":30,"keywordType":"Context","textWithKeyword":"Given Admin is on Program Confirm Deletion Page after selecting a program to delete","stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"When Admin Click on \"X\" button","stepMatchArguments":[{"group":{"start":15,"value":"\"X\"","children":[{"start":16,"value":"X","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then Admin can see Confirm Deletion form disappear","stepMatchArguments":[]}]},
  {"pwTestLine":39,"pickleLine":36,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":40,"gherkinStepLine":38,"keywordType":"Action","textWithKeyword":"When Admin selects more than one program by clicking on the checkbox","stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":39,"keywordType":"Outcome","textWithKeyword":"Then Programs get selected","stepMatchArguments":[]}]},
  {"pwTestLine":44,"pickleLine":41,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":43,"keywordType":"Action","textWithKeyword":"When Admin clicks on the delete button on the left top of the program page","stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":44,"keywordType":"Outcome","textWithKeyword":"Then Admin lands on Confirmation form","stepMatchArguments":[]}]},
  {"pwTestLine":49,"pickleLine":46,"skipped":true,"tags":["@skip"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true},{"pwStepLine":50,"gherkinStepLine":47,"keywordType":"Context","textWithKeyword":"Given Admin is on Confirm deletion form"},{"pwStepLine":51,"gherkinStepLine":48,"keywordType":"Action","textWithKeyword":"When Admin clicks on yesbutton\"Yes\" button"},{"pwStepLine":52,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then Admin can see 'SuccessfulProgram Deleted' message"}]},
  {"pwTestLine":55,"pickleLine":51,"skipped":true,"tags":["@skip"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true},{"pwStepLine":56,"gherkinStepLine":53,"keywordType":"Action","textWithKeyword":"When Admin Searches for Deleted Program names"},{"pwStepLine":57,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"Then There should be zero results"}]},
  {"pwTestLine":60,"pickleLine":56,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":57,"keywordType":"Context","textWithKeyword":"Given Admin is on Confirm deletion form-multiple programes selected to delete","stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":58,"keywordType":"Action","textWithKeyword":"When Admin clicks on nobutton\"No\" button-multiple programes selected to delete","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":59,"keywordType":"Outcome","textWithKeyword":"Then Admin can see Programs are still selected and not deleted","stepMatchArguments":[]}]},
  {"pwTestLine":66,"pickleLine":63,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":65,"keywordType":"Action","textWithKeyword":"When Admin enter the program to search By program name","stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":66,"keywordType":"Outcome","textWithKeyword":"Then Admin should able to see Program name, description, and status for searched program name","stepMatchArguments":[]}]},
  {"pwTestLine":71,"pickleLine":68,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":72,"gherkinStepLine":70,"keywordType":"Action","textWithKeyword":"When Admin enter the program to search By program description","stepMatchArguments":[]},{"pwStepLine":73,"gherkinStepLine":71,"keywordType":"Outcome","textWithKeyword":"Then Admin should able to see Program name, description, and status for searched program description","stepMatchArguments":[]}]},
  {"pwTestLine":76,"pickleLine":73,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":77,"gherkinStepLine":75,"keywordType":"Action","textWithKeyword":"When Admin enter the program to search By program name that does not exist","stepMatchArguments":[]},{"pwStepLine":78,"gherkinStepLine":76,"keywordType":"Outcome","textWithKeyword":"Then There should be zero results - Search bar","stepMatchArguments":[]}]},
  {"pwTestLine":81,"pickleLine":78,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":80,"keywordType":"Action","textWithKeyword":"When Admin enter the program to search By partial name of program","stepMatchArguments":[]},{"pwStepLine":83,"gherkinStepLine":81,"keywordType":"Outcome","textWithKeyword":"Then Admin should able to see Program name, description, and status for searched program name - for partial name search","stepMatchArguments":[]}]},
  {"pwTestLine":88,"pickleLine":91,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":89,"gherkinStepLine":86,"keywordType":"Action","textWithKeyword":"When Admin clicks on Arrow next to \"Program Name\" to sort in Ascending order","stepMatchArguments":[{"group":{"start":30,"value":"\"Program Name\"","children":[{"start":31,"value":"Program Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":90,"gherkinStepLine":87,"keywordType":"Outcome","textWithKeyword":"Then Admin See the \"Program Name\" is sorted in Ascending order","stepMatchArguments":[{"group":{"start":14,"value":"\"Program Name\"","children":[{"start":15,"value":"Program Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":93,"pickleLine":92,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":94,"gherkinStepLine":86,"keywordType":"Action","textWithKeyword":"When Admin clicks on Arrow next to \"Program Description\" to sort in Ascending order","stepMatchArguments":[{"group":{"start":30,"value":"\"Program Description\"","children":[{"start":31,"value":"Program Description","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":95,"gherkinStepLine":87,"keywordType":"Outcome","textWithKeyword":"Then Admin See the \"Program Description\" is sorted in Ascending order","stepMatchArguments":[{"group":{"start":14,"value":"\"Program Description\"","children":[{"start":15,"value":"Program Description","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":98,"pickleLine":93,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":99,"gherkinStepLine":86,"keywordType":"Action","textWithKeyword":"When Admin clicks on Arrow next to \"Program Status\" to sort in Ascending order","stepMatchArguments":[{"group":{"start":30,"value":"\"Program Status\"","children":[{"start":31,"value":"Program Status","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":100,"gherkinStepLine":87,"keywordType":"Outcome","textWithKeyword":"Then Admin See the \"Program Status\" is sorted in Ascending order","stepMatchArguments":[{"group":{"start":14,"value":"\"Program Status\"","children":[{"start":15,"value":"Program Status","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":107,"pickleLine":101,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":108,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When Admin clicks on Arrow next to \"Program Name\" to sort in Descending order","stepMatchArguments":[{"group":{"start":30,"value":"\"Program Name\"","children":[{"start":31,"value":"Program Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":109,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then Admin See the \"Program Name\" is sorted in Descending order","stepMatchArguments":[{"group":{"start":14,"value":"\"Program Name\"","children":[{"start":15,"value":"Program Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":112,"pickleLine":102,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":113,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When Admin clicks on Arrow next to \"Program Description\" to sort in Descending order","stepMatchArguments":[{"group":{"start":30,"value":"\"Program Description\"","children":[{"start":31,"value":"Program Description","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":114,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then Admin See the \"Program Description\" is sorted in Descending order","stepMatchArguments":[{"group":{"start":14,"value":"\"Program Description\"","children":[{"start":15,"value":"Program Description","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":117,"pickleLine":103,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":118,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When Admin clicks on Arrow next to \"Program Status\" to sort in Descending order","stepMatchArguments":[{"group":{"start":30,"value":"\"Program Status\"","children":[{"start":31,"value":"Program Status","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":119,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then Admin See the \"Program Status\" is sorted in Descending order","stepMatchArguments":[{"group":{"start":14,"value":"\"Program Status\"","children":[{"start":15,"value":"Program Status","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":124,"pickleLine":107,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":125,"gherkinStepLine":108,"keywordType":"Action","textWithKeyword":"When Admin clicks \"Next page\" link on the \"Program\" table","stepMatchArguments":[{"group":{"start":13,"value":"\"Next page\"","children":[{"start":14,"value":"Next page","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":37,"value":"\"Program\"","children":[{"start":38,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":126,"gherkinStepLine":109,"keywordType":"Outcome","textWithKeyword":"Then Admin should see the next page record on the table  with Pagination has previous active link enabled","stepMatchArguments":[]}]},
  {"pwTestLine":129,"pickleLine":111,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":130,"gherkinStepLine":112,"keywordType":"Action","textWithKeyword":"When Admin clicks \"Last page\" link on the \"Program\" table","stepMatchArguments":[{"group":{"start":13,"value":"\"Last page\"","children":[{"start":14,"value":"Last page","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":37,"value":"\"Program\"","children":[{"start":38,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":131,"gherkinStepLine":113,"keywordType":"Outcome","textWithKeyword":"Then Admin should see the last page record on the table with Next page link and last page links are disabled","stepMatchArguments":[]}]},
  {"pwTestLine":134,"pickleLine":115,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":135,"gherkinStepLine":116,"keywordType":"Context","textWithKeyword":"Given Admin is on last page of \"Program\" module table","stepMatchArguments":[{"group":{"start":25,"value":"\"Program\"","children":[{"start":26,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":136,"gherkinStepLine":117,"keywordType":"Action","textWithKeyword":"When Admin clicks \"Previous page\" link on the \"Program\" table","stepMatchArguments":[{"group":{"start":13,"value":"\"Previous page\"","children":[{"start":14,"value":"Previous page","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Program\"","children":[{"start":42,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":137,"gherkinStepLine":118,"keywordType":"Outcome","textWithKeyword":"Then Admin should see the previous page record on the table with pagination has next page and last page link enabled","stepMatchArguments":[]}]},
  {"pwTestLine":140,"pickleLine":120,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":141,"gherkinStepLine":121,"keywordType":"Context","textWithKeyword":"Given Admin is on last page of \"Program\" module table","stepMatchArguments":[{"group":{"start":25,"value":"\"Program\"","children":[{"start":26,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":142,"gherkinStepLine":122,"keywordType":"Action","textWithKeyword":"When Admin clicks \"First page\" link on the \"Program\" table","stepMatchArguments":[{"group":{"start":13,"value":"\"First page\"","children":[{"start":14,"value":"First page","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":38,"value":"\"Program\"","children":[{"start":39,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":143,"gherkinStepLine":123,"keywordType":"Outcome","textWithKeyword":"Then Admin should see the very first page record on the table with Previous page link and first page links are disabled","stepMatchArguments":[]}]},
  {"pwTestLine":146,"pickleLine":127,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":147,"gherkinStepLine":128,"keywordType":"Outcome","textWithKeyword":"Then Admin should land on the \" Manage Program\" page","stepMatchArguments":[{"group":{"start":25,"value":"\" Manage Program\"","children":[{"start":26,"value":" Manage Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":150,"pickleLine":130,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":151,"gherkinStepLine":131,"keywordType":"Outcome","textWithKeyword":"Then Admin should see \"Logout\" in menu bar","stepMatchArguments":[{"group":{"start":17,"value":"\"Logout\"","children":[{"start":18,"value":"Logout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end