// Generated from: features\Program.feature
import { test } from "../../Fixtures/fixtures.js";

test.describe('Program page validation', () => {

  test.beforeEach('Background', async ({ Given, classpagefixture, When }) => {
    await Given('Admin logs in to LMS application and lands on home page', null, { classpagefixture }); 
    await When('Admin clicks the "Program" Navigation bar in the Header', null, { classpagefixture }); 
  });
  
  test('Verify delete feature', async ({ When, programpagefixture, Then }) => { 
    await When('Admin clicks on delete button for a program', null, { programpagefixture }); 
    await Then('Admin will get confirm deletion popup', null, { programpagefixture }); 
  });

  test('Verify Admin is able to click \'Yes\'', async ({ Given, programpagefixture, When, Then }) => { 
    await Given('Admin is on Confirm deletion form', null, { programpagefixture }); 
    await When('Admin clicks on yesbutton"Yes" button', null, { programpagefixture }); 
    await Then('Admin can see \'SuccessfulProgram Deleted\' message', null, { programpagefixture }); 
  });

  test('Verify Admin is able to delete program', async ({ When, programpagefixture, page, Then }) => { 
    await When('Admin Searches for "Deleted Program name"', null, { programpagefixture, page }); 
    await Then('There should seee zero results.', null, { page }); 
  });

  test('Verify Admin is able to click \'No\'', async ({ Given, programpagefixture, When, Then }) => { 
    await Given('Admin is on Program Confirm Deletion Page after selecting a program to delete', null, { programpagefixture }); 
    await When('Admin clicks on nobutton"No" button', null, { programpagefixture }); 
    await Then('Admin can see Confirmation form disappears', null, { programpagefixture }); 
  });

  test('Verify Admin is able to close the window with "X"', async ({ Given, programpagefixture, When, Then }) => { 
    await Given('Admin is on Program Confirm Deletion Page after selecting a program to delete', null, { programpagefixture }); 
    await When('Admin Click on "X" button', null, { programpagefixture }); 
    await Then('Admin can see Confirm Deletion form disappear', null, { programpagefixture }); 
  });

  test('Verify Admin is able to select multiple programs', async ({ When, programpagefixture, Then }) => { 
    await When('Admin selects more than one program by clicking on the checkbox', null, { programpagefixture }); 
    await Then('Programs get selected', null, { programpagefixture }); 
  });

  test('Verify Admin is able to delete Multiple programs', async ({ When, programpagefixture, Then }) => { 
    await When('Admin clicks on the delete button on the left top of the program page', null, { programpagefixture }); 
    await Then('Admin lands on Confirmation form', null, { programpagefixture }); 
  });

  test('Verify Admin is able to click \'Yes\' - Delete multiple programes', async ({ Given, programpagefixture, When, Then }) => { 
    await Given('Admin is on Confirm deletion form', null, { programpagefixture }); 
    await When('Admin clicks on yesbutton"Yes" button', null, { programpagefixture }); 
    await Then('Admin can see \'SuccessfulProgram Deleted\' message', null, { programpagefixture }); 
  });

  test('Verify Admin is able to deleted program', async ({ When, programpagefixture, Then, page }) => { 
    await When('Admin Searches for Deleted Program names', null, { programpagefixture }); 
    await Then('There should be zero results', null, { programpagefixture, page }); 
  });

  test('Verify Admin is able to click \'No\'-multiple programes are deleted', async ({ Given, programpagefixture, When, Then }) => { 
    await Given('Admin is on Confirm deletion form-multiple programes selected to delete', null, { programpagefixture }); 
    await When('Admin clicks on nobutton"No" button-multiple programes selected to delete', null, { programpagefixture }); 
    await Then('Admin can see Programs are still selected and not deleted', null, { programpagefixture }); 
  });

  test('Verify Admin is able to search results found for program name', async ({ When, programpagefixture, page, Then }) => { 
    await When('Admin enter the program to search By program name', null, { programpagefixture, page }); 
    await Then('Admin should able to see Program name, description, and status for searched program name', null, { page }); 
  });

  test('Verify Admin is able to search results found for program description', async ({ When, programpagefixture, page, Then }) => { 
    await When('Admin enter the program to search By program description', null, { programpagefixture, page }); 
    await Then('Admin should able to see Program name, description, and status for searched program description', null, { page }); 
  });

  test('Verify Admin is able to search results not found', async ({ When, programpagefixture, page, Then }) => { 
    await When('Admin enter the program to search By program name that does not exist', null, { programpagefixture, page }); 
    await Then('There should be zero results - Search bar', null, { page }); 
  });

  test('Verify Admin is able to search with partial program name', async ({ When, programpagefixture, page, Then }) => { 
    await When('Admin enter the program to search By partial name of program', null, { programpagefixture, page }); 
    await Then('Admin should able to see Program name, description, and status for searched program name - for partial name search', null, { page }); 
  });

  test.describe('Verify sorting of "<column Name>" in Ascending order', () => {

    test('Verify sorting of "Program Name" in Ascending order', async ({ When, commonpagefixture, Then }) => { 
      await When('Admin clicks on Arrow next to "Program Name" to sort in Ascending order', null, { commonpagefixture }); 
      await Then('Admin See the "Program Name" is sorted in Ascending order', null, { commonpagefixture }); 
    });

    test('Verify sorting of "Program Description" in Ascending order', async ({ When, commonpagefixture, Then }) => { 
      await When('Admin clicks on Arrow next to "Program Description" to sort in Ascending order', null, { commonpagefixture }); 
      await Then('Admin See the "Program Description" is sorted in Ascending order', null, { commonpagefixture }); 
    });

    test('Verify sorting of "Program Status" in Ascending order', async ({ When, commonpagefixture, Then }) => { 
      await When('Admin clicks on Arrow next to "Program Status" to sort in Ascending order', null, { commonpagefixture }); 
      await Then('Admin See the "Program Status" is sorted in Ascending order', null, { commonpagefixture }); 
    });

  });

  test.describe('Verify sorting of "<column Name>" in Descending order', () => {

    test('Verify sorting of "Program Name" in Descending order', async ({ When, commonpagefixture, Then }) => { 
      await When('Admin clicks on Arrow next to "Program Name" to sort in Descending order', null, { commonpagefixture }); 
      await Then('Admin See the "Program Name" is sorted in Descending order', null, { commonpagefixture }); 
    });

    test('Verify sorting of "Program Description" in Descending order', async ({ When, commonpagefixture, Then }) => { 
      await When('Admin clicks on Arrow next to "Program Description" to sort in Descending order', null, { commonpagefixture }); 
      await Then('Admin See the "Program Description" is sorted in Descending order', null, { commonpagefixture }); 
    });

    test('Verify sorting of "Program Status" in Descending order', async ({ When, commonpagefixture, Then }) => { 
      await When('Admin clicks on Arrow next to "Program Status" to sort in Descending order', null, { commonpagefixture }); 
      await Then('Admin See the "Program Status" is sorted in Descending order', null, { commonpagefixture }); 
    });

  });

  test('Verify Admin is able to click \'Next page\' link', async ({ When, commonpagefixture, Then }) => { 
    await When('Admin clicks "Next page" link on the "Program" table', null, { commonpagefixture }); 
    await Then('Admin should see the next page record on the table  with Pagination has previous active link enabled', null, { commonpagefixture }); 
  });

  test('Verify Admin is able to click \'Last page\' link', async ({ When, commonpagefixture, Then }) => { 
    await When('Admin clicks "Last page" link on the "Program" table', null, { commonpagefixture }); 
    await Then('Admin should see the last page record on the table with Next page link and last page links are disabled', null, { commonpagefixture }); 
  });

  test('Verify Admin is able to click \'Previous page\' link', async ({ Given, commonpagefixture, When, Then }) => { 
    await Given('Admin is on last page of "Program" module table', null, { commonpagefixture }); 
    await When('Admin clicks "Previous page" link on the "Program" table', null, { commonpagefixture }); 
    await Then('Admin should see the previous page record on the table with pagination has next page and last page link enabled', null, { commonpagefixture }); 
  });

  test.only('Verify Admin is able to click First page link', { tag: ['@only'] }, async ({ Given, commonpagefixture, When, Then }) => { 
    await Given('Admin is on last page of "Program" module table', null, { commonpagefixture }); 
    await When('Admin clicks "First page" link on the "Program" table', null, { commonpagefixture }); 
    await Then('Admin should see the very first page record on the table with Previous page link and first page links are disabled', null, { commonpagefixture }); 
  });

  test('Validating the program manage page', async ({ Then, classpagefixture }) => { 
    await Then('Admin should land on the " Manage Program" page', null, { classpagefixture }); 
  });

  test('Verify Logout displayed in menu bar', async ({ Then, programpagefixture }) => { 
    await Then('Admin should see "Logout" in menu bar', null, { programpagefixture }); 
  });

});

// == technical section ==

test.afterEach('AfterEach Hooks', ({ $afterEach }) => {});

test.use({
  $test: ({}, use) => use(test),
  $uri: ({}, use) => use('features\\Program.feature'),
  $bddFileData: ({}, use) => use(bddFileData),
  $afterEachFixtures: ({ page }, use) => use({ page }),
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":11,"pickleLine":10,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When Admin clicks on delete button for a program","stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then Admin will get confirm deletion popup","stepMatchArguments":[]}]},
  {"pwTestLine":16,"pickleLine":15,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":17,"gherkinStepLine":16,"keywordType":"Context","textWithKeyword":"Given Admin is on Confirm deletion form","stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":17,"keywordType":"Action","textWithKeyword":"When Admin clicks on yesbutton\"Yes\" button","stepMatchArguments":[{"group":{"start":25,"value":"\"Yes\"","children":[{"start":26,"value":"Yes","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":19,"gherkinStepLine":18,"keywordType":"Outcome","textWithKeyword":"Then Admin can see 'SuccessfulProgram Deleted' message","stepMatchArguments":[{"group":{"start":14,"value":"'SuccessfulProgram Deleted'","children":[{"children":[{"children":[]}]},{"start":15,"value":"SuccessfulProgram Deleted","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":22,"pickleLine":20,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":23,"gherkinStepLine":22,"keywordType":"Action","textWithKeyword":"When Admin Searches for \"Deleted Program name\"","stepMatchArguments":[{"group":{"start":19,"value":"\"Deleted Program name\"","children":[{"start":20,"value":"Deleted Program name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":23,"keywordType":"Outcome","textWithKeyword":"Then There should seee zero results.","stepMatchArguments":[]}]},
  {"pwTestLine":27,"pickleLine":25,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":26,"keywordType":"Context","textWithKeyword":"Given Admin is on Program Confirm Deletion Page after selecting a program to delete","stepMatchArguments":[]},{"pwStepLine":29,"gherkinStepLine":27,"keywordType":"Action","textWithKeyword":"When Admin clicks on nobutton\"No\" button","stepMatchArguments":[{"group":{"start":24,"value":"\"No\"","children":[{"start":25,"value":"No","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":28,"keywordType":"Outcome","textWithKeyword":"Then Admin can see Confirmation form disappears","stepMatchArguments":[]}]},
  {"pwTestLine":33,"pickleLine":30,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":34,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given Admin is on Program Confirm Deletion Page after selecting a program to delete","stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":32,"keywordType":"Action","textWithKeyword":"When Admin Click on \"X\" button","stepMatchArguments":[{"group":{"start":15,"value":"\"X\"","children":[{"start":16,"value":"X","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":33,"keywordType":"Outcome","textWithKeyword":"Then Admin can see Confirm Deletion form disappear","stepMatchArguments":[]}]},
  {"pwTestLine":39,"pickleLine":37,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":40,"gherkinStepLine":39,"keywordType":"Action","textWithKeyword":"When Admin selects more than one program by clicking on the checkbox","stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"Then Programs get selected","stepMatchArguments":[]}]},
  {"pwTestLine":44,"pickleLine":42,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":44,"keywordType":"Action","textWithKeyword":"When Admin clicks on the delete button on the left top of the program page","stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then Admin lands on Confirmation form","stepMatchArguments":[]}]},
  {"pwTestLine":49,"pickleLine":47,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":50,"gherkinStepLine":48,"keywordType":"Context","textWithKeyword":"Given Admin is on Confirm deletion form","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":49,"keywordType":"Action","textWithKeyword":"When Admin clicks on yesbutton\"Yes\" button","stepMatchArguments":[{"group":{"start":25,"value":"\"Yes\"","children":[{"start":26,"value":"Yes","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":52,"gherkinStepLine":50,"keywordType":"Outcome","textWithKeyword":"Then Admin can see 'SuccessfulProgram Deleted' message","stepMatchArguments":[{"group":{"start":14,"value":"'SuccessfulProgram Deleted'","children":[{"children":[{"children":[]}]},{"start":15,"value":"SuccessfulProgram Deleted","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":55,"pickleLine":52,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":54,"keywordType":"Action","textWithKeyword":"When Admin Searches for Deleted Program names","stepMatchArguments":[]},{"pwStepLine":57,"gherkinStepLine":55,"keywordType":"Outcome","textWithKeyword":"Then There should be zero results","stepMatchArguments":[]}]},
  {"pwTestLine":60,"pickleLine":57,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":58,"keywordType":"Context","textWithKeyword":"Given Admin is on Confirm deletion form-multiple programes selected to delete","stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":59,"keywordType":"Action","textWithKeyword":"When Admin clicks on nobutton\"No\" button-multiple programes selected to delete","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":60,"keywordType":"Outcome","textWithKeyword":"Then Admin can see Programs are still selected and not deleted","stepMatchArguments":[]}]},
  {"pwTestLine":66,"pickleLine":64,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":66,"keywordType":"Action","textWithKeyword":"When Admin enter the program to search By program name","stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":67,"keywordType":"Outcome","textWithKeyword":"Then Admin should able to see Program name, description, and status for searched program name","stepMatchArguments":[]}]},
  {"pwTestLine":71,"pickleLine":69,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":72,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When Admin enter the program to search By program description","stepMatchArguments":[]},{"pwStepLine":73,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then Admin should able to see Program name, description, and status for searched program description","stepMatchArguments":[]}]},
  {"pwTestLine":76,"pickleLine":74,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":77,"gherkinStepLine":76,"keywordType":"Action","textWithKeyword":"When Admin enter the program to search By program name that does not exist","stepMatchArguments":[]},{"pwStepLine":78,"gherkinStepLine":77,"keywordType":"Outcome","textWithKeyword":"Then There should be zero results - Search bar","stepMatchArguments":[]}]},
  {"pwTestLine":81,"pickleLine":79,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":81,"keywordType":"Action","textWithKeyword":"When Admin enter the program to search By partial name of program","stepMatchArguments":[]},{"pwStepLine":83,"gherkinStepLine":82,"keywordType":"Outcome","textWithKeyword":"Then Admin should able to see Program name, description, and status for searched program name - for partial name search","stepMatchArguments":[]}]},
  {"pwTestLine":88,"pickleLine":91,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":89,"gherkinStepLine":87,"keywordType":"Action","textWithKeyword":"When Admin clicks on Arrow next to \"Program Name\" to sort in Ascending order","stepMatchArguments":[{"group":{"start":30,"value":"\"Program Name\"","children":[{"start":31,"value":"Program Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":90,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"Then Admin See the \"Program Name\" is sorted in Ascending order","stepMatchArguments":[{"group":{"start":14,"value":"\"Program Name\"","children":[{"start":15,"value":"Program Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":93,"pickleLine":92,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":94,"gherkinStepLine":87,"keywordType":"Action","textWithKeyword":"When Admin clicks on Arrow next to \"Program Description\" to sort in Ascending order","stepMatchArguments":[{"group":{"start":30,"value":"\"Program Description\"","children":[{"start":31,"value":"Program Description","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":95,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"Then Admin See the \"Program Description\" is sorted in Ascending order","stepMatchArguments":[{"group":{"start":14,"value":"\"Program Description\"","children":[{"start":15,"value":"Program Description","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":98,"pickleLine":93,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":99,"gherkinStepLine":87,"keywordType":"Action","textWithKeyword":"When Admin clicks on Arrow next to \"Program Status\" to sort in Ascending order","stepMatchArguments":[{"group":{"start":30,"value":"\"Program Status\"","children":[{"start":31,"value":"Program Status","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":100,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"Then Admin See the \"Program Status\" is sorted in Ascending order","stepMatchArguments":[{"group":{"start":14,"value":"\"Program Status\"","children":[{"start":15,"value":"Program Status","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":107,"pickleLine":100,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":108,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When Admin clicks on Arrow next to \"Program Name\" to sort in Descending order","stepMatchArguments":[{"group":{"start":30,"value":"\"Program Name\"","children":[{"start":31,"value":"Program Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":109,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then Admin See the \"Program Name\" is sorted in Descending order","stepMatchArguments":[{"group":{"start":14,"value":"\"Program Name\"","children":[{"start":15,"value":"Program Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":112,"pickleLine":101,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":113,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When Admin clicks on Arrow next to \"Program Description\" to sort in Descending order","stepMatchArguments":[{"group":{"start":30,"value":"\"Program Description\"","children":[{"start":31,"value":"Program Description","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":114,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then Admin See the \"Program Description\" is sorted in Descending order","stepMatchArguments":[{"group":{"start":14,"value":"\"Program Description\"","children":[{"start":15,"value":"Program Description","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":117,"pickleLine":102,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":118,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When Admin clicks on Arrow next to \"Program Status\" to sort in Descending order","stepMatchArguments":[{"group":{"start":30,"value":"\"Program Status\"","children":[{"start":31,"value":"Program Status","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":119,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then Admin See the \"Program Status\" is sorted in Descending order","stepMatchArguments":[{"group":{"start":14,"value":"\"Program Status\"","children":[{"start":15,"value":"Program Status","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":124,"pickleLine":106,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":125,"gherkinStepLine":107,"keywordType":"Action","textWithKeyword":"When Admin clicks \"Next page\" link on the \"Program\" table","stepMatchArguments":[{"group":{"start":13,"value":"\"Next page\"","children":[{"start":14,"value":"Next page","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":37,"value":"\"Program\"","children":[{"start":38,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":126,"gherkinStepLine":108,"keywordType":"Outcome","textWithKeyword":"Then Admin should see the next page record on the table  with Pagination has previous active link enabled","stepMatchArguments":[]}]},
  {"pwTestLine":129,"pickleLine":110,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":130,"gherkinStepLine":111,"keywordType":"Action","textWithKeyword":"When Admin clicks \"Last page\" link on the \"Program\" table","stepMatchArguments":[{"group":{"start":13,"value":"\"Last page\"","children":[{"start":14,"value":"Last page","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":37,"value":"\"Program\"","children":[{"start":38,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":131,"gherkinStepLine":112,"keywordType":"Outcome","textWithKeyword":"Then Admin should see the last page record on the table with Next page link and last page links are disabled","stepMatchArguments":[]}]},
  {"pwTestLine":134,"pickleLine":114,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":135,"gherkinStepLine":115,"keywordType":"Context","textWithKeyword":"Given Admin is on last page of \"Program\" module table","stepMatchArguments":[{"group":{"start":25,"value":"\"Program\"","children":[{"start":26,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":136,"gherkinStepLine":116,"keywordType":"Action","textWithKeyword":"When Admin clicks \"Previous page\" link on the \"Program\" table","stepMatchArguments":[{"group":{"start":13,"value":"\"Previous page\"","children":[{"start":14,"value":"Previous page","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Program\"","children":[{"start":42,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":137,"gherkinStepLine":117,"keywordType":"Outcome","textWithKeyword":"Then Admin should see the previous page record on the table with pagination has next page and last page link enabled","stepMatchArguments":[]}]},
  {"pwTestLine":140,"pickleLine":119,"tags":["@only"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":141,"gherkinStepLine":120,"keywordType":"Context","textWithKeyword":"Given Admin is on last page of \"Program\" module table","stepMatchArguments":[{"group":{"start":25,"value":"\"Program\"","children":[{"start":26,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":142,"gherkinStepLine":121,"keywordType":"Action","textWithKeyword":"When Admin clicks \"First page\" link on the \"Program\" table","stepMatchArguments":[{"group":{"start":13,"value":"\"First page\"","children":[{"start":14,"value":"First page","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":38,"value":"\"Program\"","children":[{"start":39,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":143,"gherkinStepLine":122,"keywordType":"Outcome","textWithKeyword":"Then Admin should see the very first page record on the table with Previous page link and first page links are disabled","stepMatchArguments":[]}]},
  {"pwTestLine":146,"pickleLine":126,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":147,"gherkinStepLine":127,"keywordType":"Outcome","textWithKeyword":"Then Admin should land on the \" Manage Program\" page","stepMatchArguments":[{"group":{"start":25,"value":"\" Manage Program\"","children":[{"start":26,"value":" Manage Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":150,"pickleLine":129,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given Admin logs in to LMS application and lands on home page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When Admin clicks the \"Program\" Navigation bar in the Header","isBg":true,"stepMatchArguments":[{"group":{"start":17,"value":"\"Program\"","children":[{"start":18,"value":"Program","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":151,"gherkinStepLine":130,"keywordType":"Outcome","textWithKeyword":"Then Admin should see \"Logout\" in menu bar","stepMatchArguments":[{"group":{"start":17,"value":"\"Logout\"","children":[{"start":18,"value":"Logout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end